import { ArrowLeft, AlertTriangle, Shield, TrendingUp, FileCode, CheckCircle2, Copy, Download, Github, ExternalLink } from 'lucide-react';
import { Button } from './ui/button';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { Separator } from './ui/separator';
import { Progress } from './ui/progress';
import type { AnalysisResult } from '../App';
import { toast } from 'sonner';

interface ResultsPageProps {
  result: AnalysisResult;
  onBack: () => void;
}

export function ResultsPage({ result, onBack }: ResultsPageProps) {
  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical':
        return 'bg-red-100 text-red-800 border-red-200';
      case 'high':
        return 'bg-orange-100 text-orange-800 border-orange-200';
      case 'medium':
        return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      case 'low':
        return 'bg-blue-100 text-blue-800 border-blue-200';
      default:
        return 'bg-slate-100 text-slate-800 border-slate-200';
    }
  };

  const getRiskColor = (risk: string) => {
    switch (risk) {
      case 'critical':
        return 'bg-red-500';
      case 'high':
        return 'bg-orange-500';
      case 'medium':
        return 'bg-yellow-500';
      case 'low':
        return 'bg-emerald-500';
      default:
        return 'bg-slate-300';
    }
  };

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-emerald-600';
    if (score >= 60) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getScoreBgColor = (score: number) => {
    if (score >= 80) return 'bg-emerald-500';
    if (score >= 60) return 'bg-yellow-500';
    return 'bg-red-500';
  };

  const handleCopyMarkdown = () => {
    const markdown = generateMarkdownReport();
    navigator.clipboard.writeText(markdown);
    toast.success('Review copied to clipboard!');
  };

  const handleDownloadJSON = () => {
    const dataStr = JSON.stringify(result, null, 2);
    const dataUri = 'data:application/json;charset=utf-8,' + encodeURIComponent(dataStr);
    const exportFileDefaultName = 'pr-review-analysis.json';
    
    const linkElement = document.createElement('a');
    linkElement.setAttribute('href', dataUri);
    linkElement.setAttribute('download', exportFileDefaultName);
    linkElement.click();
    toast.success('Analysis downloaded!');
  };

  const generateMarkdownReport = () => {
    return `# PR Code Review Analysis

## Summary
${result.pr_summary.what_changed}

**Why:** ${result.pr_summary.why_it_changed}

**Key Files:**
${result.pr_summary.key_files.map(f => `- ${f}`).join('\n')}

## Merge Readiness: ${result.merge_readiness.score}/100

${result.merge_readiness.blockers.length > 0 ? '### 🚫 Blockers\n' + result.merge_readiness.blockers.map(b => `- ${b}`).join('\n') : ''}

## Top Findings

${result.findings.slice(0, 5).map((f, i) => `
### ${i + 1}. ${f.title} \`[${f.severity.toUpperCase()}]\`
**File:** \`${f.file}\`  
**Evidence:** ${f.evidence}  
**Recommendation:** ${f.recommendation}
`).join('\n')}

## Risk Assessment
- **Security:** ${result.risk_matrix.security}
- **Performance:** ${result.risk_matrix.performance}
- **Breaking Changes:** ${result.risk_matrix.breaking_change}
- **Maintainability:** ${result.risk_matrix.maintainability}

---
*Generated by AI PR Reviewer*`;
  };

  const topFindings = result.findings.slice(0, 3);
  const criticalCount = result.findings.filter(f => f.severity === 'critical').length;
  const highCount = result.findings.filter(f => f.severity === 'high').length;

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="border-b bg-white sticky top-0 z-10 shadow-sm">
        <div className="container mx-auto px-4 py-4 max-w-7xl">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="sm" onClick={onBack}>
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back
              </Button>
              <Separator orientation="vertical" className="h-6" />
              <div>
                <h1 className="font-semibold text-slate-900">PR Analysis Results</h1>
                <p className="text-sm text-slate-500">
                  {result.findings.length} findings • {result.pr_summary.key_files.length} files changed
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={handleCopyMarkdown}>
                <Copy className="w-4 h-4 mr-2" />
                Copy as Markdown
              </Button>
              <Button variant="outline" size="sm" onClick={handleDownloadJSON}>
                <Download className="w-4 h-4 mr-2" />
                Export JSON
              </Button>
              <Button variant="outline" size="sm" disabled>
                <Github className="w-4 h-4 mr-2" />
                Post to PR
              </Button>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8 max-w-7xl">
        {/* Top Stats */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-slate-500 mb-1">Merge Readiness</p>
                  <p className={`text-3xl ${getScoreColor(result.merge_readiness.score)}`}>
                    {result.merge_readiness.score}
                  </p>
                </div>
                <div className="w-16 h-16 rounded-full border-4 border-slate-100 flex items-center justify-center">
                  <div className={`w-12 h-12 rounded-full ${getScoreBgColor(result.merge_readiness.score)} flex items-center justify-center text-white`}>
                    {result.merge_readiness.score}
                  </div>
                </div>
              </div>
              <Progress value={result.merge_readiness.score} className="mt-3" />
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-slate-500 mb-1">Total Findings</p>
                  <p className="text-3xl text-slate-900">{result.findings.length}</p>
                </div>
                <AlertTriangle className="w-10 h-10 text-slate-400" />
              </div>
              <div className="flex gap-2 mt-3 text-xs">
                {criticalCount > 0 && <Badge variant="destructive">{criticalCount} Critical</Badge>}
                {highCount > 0 && <Badge className="bg-orange-100 text-orange-800">{highCount} High</Badge>}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-slate-500 mb-1">Security Risk</p>
                  <p className="text-3xl text-slate-900 capitalize">{result.risk_matrix.security}</p>
                </div>
                <Shield className="w-10 h-10 text-slate-400" />
              </div>
              <div className={`h-2 rounded-full mt-3 ${getRiskColor(result.risk_matrix.security)}`} />
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-slate-500 mb-1">Files Changed</p>
                  <p className="text-3xl text-slate-900">{result.pr_summary.key_files.length}</p>
                </div>
                <FileCode className="w-10 h-10 text-slate-400" />
              </div>
              <p className="text-xs text-slate-500 mt-3">
                Across multiple modules
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Top 3 Issues Alert */}
        {topFindings.length > 0 && (
          <Card className="mb-8 border-orange-200 bg-orange-50">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-orange-900">
                <AlertTriangle className="w-5 h-5" />
                Top Priority Issues
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {topFindings.map((finding, index) => (
                <div key={index} className="p-4 bg-white rounded-lg border border-orange-200">
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex items-start gap-3 flex-1">
                      <span className="flex items-center justify-center w-6 h-6 rounded-full bg-orange-100 text-orange-700 text-sm shrink-0">
                        {index + 1}
                      </span>
                      <div className="flex-1">
                        <h4 className="font-medium text-slate-900 mb-1">{finding.title}</h4>
                        <p className="text-sm text-slate-600 mb-2">{finding.file}</p>
                        <p className="text-sm text-slate-700 bg-slate-50 p-3 rounded border border-slate-200 font-mono">
                          {finding.evidence}
                        </p>
                      </div>
                    </div>
                    <Badge className={getSeverityColor(finding.severity)}>
                      {finding.severity}
                    </Badge>
                  </div>
                  <div className="ml-9 mt-3 p-3 bg-blue-50 border border-blue-200 rounded">
                    <p className="text-sm text-slate-700">
                      <span className="font-medium">💡 Recommendation:</span> {finding.recommendation}
                    </p>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        )}

        {/* Main Content Tabs */}
        <Tabs defaultValue="summary" className="space-y-6">
          <TabsList className="grid w-full grid-cols-5">
            <TabsTrigger value="summary">Summary</TabsTrigger>
            <TabsTrigger value="findings">
              All Findings ({result.findings.length})
            </TabsTrigger>
            <TabsTrigger value="risks">Risk Matrix</TabsTrigger>
            <TabsTrigger value="tests">Test Plan</TabsTrigger>
            <TabsTrigger value="readiness">Merge Review</TabsTrigger>
          </TabsList>

          {/* Summary Tab */}
          <TabsContent value="summary" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>PR Summary</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <h4 className="text-sm font-medium text-slate-700 mb-2">What Changed</h4>
                  <p className="text-slate-900">{result.pr_summary.what_changed}</p>
                </div>
                <Separator />
                <div>
                  <h4 className="text-sm font-medium text-slate-700 mb-2">Why It Changed</h4>
                  <p className="text-slate-900">{result.pr_summary.why_it_changed}</p>
                </div>
                <Separator />
                <div>
                  <h4 className="text-sm font-medium text-slate-700 mb-2">Key Files Modified</h4>
                  <div className="space-y-2">
                    {result.pr_summary.key_files.map((file, index) => (
                      <div key={index} className="flex items-center gap-2 p-2 bg-slate-50 rounded border border-slate-200">
                        <FileCode className="w-4 h-4 text-slate-400" />
                        <code className="text-sm text-slate-900">{file}</code>
                        <Button variant="ghost" size="sm" className="ml-auto h-7">
                          <ExternalLink className="w-3 h-3" />
                        </Button>
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* All Findings Tab */}
          <TabsContent value="findings" className="space-y-4">
            {result.findings.map((finding, index) => (
              <Card key={index}>
                <CardContent className="pt-6">
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <Badge className={getSeverityColor(finding.severity)}>
                          {finding.severity}
                        </Badge>
                        <span className="text-xs text-slate-500">
                          Confidence: {Math.round(finding.confidence * 100)}%
                        </span>
                      </div>
                      <h3 className="text-lg font-medium text-slate-900 mb-2">{finding.title}</h3>
                      <p className="text-sm text-slate-600 flex items-center gap-2">
                        <FileCode className="w-4 h-4" />
                        {finding.file}
                      </p>
                    </div>
                  </div>
                  
                  <div className="space-y-3">
                    <div className="p-3 bg-slate-50 border border-slate-200 rounded">
                      <p className="text-xs font-medium text-slate-700 mb-1">Evidence</p>
                      <p className="text-sm text-slate-900 font-mono">{finding.evidence}</p>
                    </div>
                    
                    <div className="p-3 bg-blue-50 border border-blue-200 rounded">
                      <p className="text-xs font-medium text-blue-900 mb-1">💡 Recommendation</p>
                      <p className="text-sm text-slate-900">{finding.recommendation}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </TabsContent>

          {/* Risk Matrix Tab */}
          <TabsContent value="risks">
            <Card>
              <CardHeader>
                <CardTitle>Risk Assessment Matrix</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <Shield className="w-5 h-5 text-slate-600" />
                          <span className="font-medium text-slate-900">Security</span>
                        </div>
                        <Badge className={getSeverityColor(result.risk_matrix.security)}>
                          {result.risk_matrix.security}
                        </Badge>
                      </div>
                      <div className={`h-3 rounded-full ${getRiskColor(result.risk_matrix.security)}`} />
                      <p className="text-sm text-slate-600 mt-2">
                        Authentication changes and potential bypass vulnerabilities detected
                      </p>
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <TrendingUp className="w-5 h-5 text-slate-600" />
                          <span className="font-medium text-slate-900">Performance</span>
                        </div>
                        <Badge className={getSeverityColor(result.risk_matrix.performance)}>
                          {result.risk_matrix.performance}
                        </Badge>
                      </div>
                      <div className={`h-3 rounded-full ${getRiskColor(result.risk_matrix.performance)}`} />
                      <p className="text-sm text-slate-600 mt-2">
                        JWT validation may impact response times on high-traffic endpoints
                      </p>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <AlertTriangle className="w-5 h-5 text-slate-600" />
                          <span className="font-medium text-slate-900">Breaking Changes</span>
                        </div>
                        <Badge className={getSeverityColor(result.risk_matrix.breaking_change)}>
                          {result.risk_matrix.breaking_change}
                        </Badge>
                      </div>
                      <div className={`h-3 rounded-full ${getRiskColor(result.risk_matrix.breaking_change)}`} />
                      <p className="text-sm text-slate-600 mt-2">
                        Session-based auth migration requires client updates
                      </p>
                    </div>

                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <FileCode className="w-5 h-5 text-slate-600" />
                          <span className="font-medium text-slate-900">Maintainability</span>
                        </div>
                        <Badge className={getSeverityColor(result.risk_matrix.maintainability)}>
                          {result.risk_matrix.maintainability}
                        </Badge>
                      </div>
                      <div className={`h-3 rounded-full ${getRiskColor(result.risk_matrix.maintainability)}`} />
                      <p className="text-sm text-slate-600 mt-2">
                        Code is well-structured but lacks comprehensive error logging
                      </p>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Test Plan Tab */}
          <TabsContent value="tests" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Unit Tests</CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {result.test_plan.unit_tests.map((test, index) => (
                    <li key={index} className="flex items-start gap-3 p-3 bg-slate-50 rounded border border-slate-200">
                      <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                      <span className="text-slate-900">{test}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Integration Tests</CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {result.test_plan.integration_tests.map((test, index) => (
                    <li key={index} className="flex items-start gap-3 p-3 bg-slate-50 rounded border border-slate-200">
                      <CheckCircle2 className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
                      <span className="text-slate-900">{test}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Edge Cases & Scenarios</CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {result.test_plan.edge_cases.map((test, index) => (
                    <li key={index} className="flex items-start gap-3 p-3 bg-slate-50 rounded border border-slate-200">
                      <CheckCircle2 className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
                      <span className="text-slate-900">{test}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Merge Readiness Tab */}
          <TabsContent value="readiness">
            <Card>
              <CardHeader>
                <CardTitle>Merge Readiness Assessment</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="text-center py-8">
                  <div className={`inline-flex items-center justify-center w-32 h-32 rounded-full ${getScoreBgColor(result.merge_readiness.score)} text-white mb-4`}>
                    <span className="text-5xl">{result.merge_readiness.score}</span>
                  </div>
                  <p className="text-lg text-slate-600">Overall Merge Readiness Score</p>
                  <Progress value={result.merge_readiness.score} className="max-w-md mx-auto mt-4" />
                </div>

                {result.merge_readiness.blockers.length > 0 && (
                  <>
                    <Separator />
                    <div>
                      <h4 className="font-medium text-slate-900 mb-3 flex items-center gap-2">
                        <AlertTriangle className="w-5 h-5 text-red-600" />
                        Merge Blockers
                      </h4>
                      <div className="space-y-2">
                        {result.merge_readiness.blockers.map((blocker, index) => (
                          <div key={index} className="p-3 bg-red-50 border border-red-200 rounded text-red-900">
                            {blocker}
                          </div>
                        ))}
                      </div>
                    </div>
                  </>
                )}

                <Separator />
                <div>
                  <h4 className="font-medium text-slate-900 mb-2">Additional Notes</h4>
                  <p className="text-slate-700 p-4 bg-slate-50 rounded border border-slate-200">
                    {result.merge_readiness.notes}
                  </p>
                </div>

                <Separator />
                <div className="flex items-center justify-between p-4 bg-blue-50 rounded border border-blue-200">
                  <div>
                    <p className="font-medium text-blue-900 mb-1">Ready to merge?</p>
                    <p className="text-sm text-blue-700">
                      {result.merge_readiness.score >= 80
                        ? 'This PR looks good to merge after addressing minor issues.'
                        : result.merge_readiness.score >= 60
                        ? 'Address the identified blockers before merging.'
                        : 'This PR needs significant work before it can be merged.'}
                    </p>
                  </div>
                  <Button disabled variant={result.merge_readiness.score >= 80 ? 'default' : 'secondary'}>
                    <Github className="w-4 h-4 mr-2" />
                    Post Review
                  </Button>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}
